project_id = "nfzmnkpepfrubjpifnna"

[auth]
enable_signup = true
enable_confirmations = false

[functions.create-credit-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.slack-deployment-notification]
verify_jwt = false

[functions.slack-bot-handler]
verify_jwt = false

[functions.deploy-to-production]
verify_jwt = false

[functions.spaceship-domain-search]
verify_jwt = false